install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script:
  - nmake /f Makefile.vc

notifications:
  - provider: Slack
    auth_token:
      secure: X+ymndzchVeC2LYsehzOt6CXEE+3wWDMYHJuOnFXIOHm8ByI2sHXCWRYQaDeSQs+iawQR9QvuRla/BSmtZBfow==
    channel: ci